-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_recv_krnl_port_status_handler is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    useConn_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    useConn_empty_n : IN STD_LOGIC;
    useConn_read : OUT STD_LOGIC;
    s_axis_tcp_port_status_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    s_axis_tcp_port_status_TVALID : IN STD_LOGIC;
    s_axis_tcp_port_status_TREADY : OUT STD_LOGIC;
    s_axis_tcp_port_status_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_tcp_port_status_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_tcp_port_status_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of hls_recv_krnl_port_status_handler is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal useConn_blk_n : STD_LOGIC;
    signal s_axis_tcp_port_status_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln742_fu_85_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal useConn_read_reg_90 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln742_fu_75_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal i_reg_64 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal zext_ln742_fu_81_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_reg_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln742_fu_85_p2 = ap_const_lv1_1) and (s_axis_tcp_port_status_TVALID = ap_const_logic_0))) and (icmp_ln742_fu_85_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_reg_64 <= add_ln742_fu_75_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (useConn_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_64 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                useConn_read_reg_90 <= useConn_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, useConn_empty_n, s_axis_tcp_port_status_TVALID, ap_CS_fsm_state2, icmp_ln742_fu_85_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (useConn_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln742_fu_85_p2 = ap_const_lv1_1) and (s_axis_tcp_port_status_TVALID = ap_const_logic_0))) and (icmp_ln742_fu_85_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((icmp_ln742_fu_85_p2 = ap_const_lv1_1) and (s_axis_tcp_port_status_TVALID = ap_const_logic_0))) and (icmp_ln742_fu_85_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln742_fu_75_p2 <= std_logic_vector(unsigned(i_reg_64) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, useConn_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (useConn_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(s_axis_tcp_port_status_TVALID, icmp_ln742_fu_85_p2)
    begin
                ap_block_state2 <= ((icmp_ln742_fu_85_p2 = ap_const_lv1_1) and (s_axis_tcp_port_status_TVALID = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln742_fu_85_p2 <= "1" when (signed(zext_ln742_fu_81_p1) < signed(useConn_read_reg_90)) else "0";

    s_axis_tcp_port_status_TDATA_blk_n_assign_proc : process(s_axis_tcp_port_status_TVALID, ap_CS_fsm_state2, icmp_ln742_fu_85_p2)
    begin
        if (((icmp_ln742_fu_85_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            s_axis_tcp_port_status_TDATA_blk_n <= s_axis_tcp_port_status_TVALID;
        else 
            s_axis_tcp_port_status_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_tcp_port_status_TREADY_assign_proc : process(s_axis_tcp_port_status_TVALID, ap_CS_fsm_state2, icmp_ln742_fu_85_p2)
    begin
        if ((not(((icmp_ln742_fu_85_p2 = ap_const_lv1_1) and (s_axis_tcp_port_status_TVALID = ap_const_logic_0))) and (icmp_ln742_fu_85_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            s_axis_tcp_port_status_TREADY <= ap_const_logic_1;
        else 
            s_axis_tcp_port_status_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    useConn_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, useConn_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            useConn_blk_n <= useConn_empty_n;
        else 
            useConn_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    useConn_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, useConn_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (useConn_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            useConn_read <= ap_const_logic_1;
        else 
            useConn_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln742_fu_81_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_64),32));
end behav;
