-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_recv_krnl_tie_off_tcp_close_con is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axis_tcp_close_connection_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axis_tcp_close_connection_TVALID : OUT STD_LOGIC;
    m_axis_tcp_close_connection_TREADY : IN STD_LOGIC;
    m_axis_tcp_close_connection_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axis_tcp_close_connection_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axis_tcp_close_connection_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of hls_recv_krnl_tie_off_tcp_close_con is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal m_axis_tcp_close_connection_TDATA_blk_n : STD_LOGIC;
    signal tmp_nbreadreq_fu_38_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_reg_76 : STD_LOGIC_VECTOR (0 downto 0);
    signal closeConnection_empty_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state1_io : BOOLEAN;
    signal regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal m_axis_tcp_close_connection_TVALID_int_regslice : STD_LOGIC;
    signal m_axis_tcp_close_connection_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_m_axis_tcp_close_connection_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_tcp_close_connection_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_tcp_close_connection_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_tcp_close_connection_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_tcp_close_connection_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_tcp_close_connection_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_tcp_close_connection_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_tcp_close_connection_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_tcp_close_connection_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_tcp_close_connection_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hls_recv_krnl_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_m_axis_tcp_close_connection_V_data_V_U : component hls_recv_krnl_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv16_0,
        vld_in => m_axis_tcp_close_connection_TVALID_int_regslice,
        ack_in => m_axis_tcp_close_connection_TREADY_int_regslice,
        data_out => m_axis_tcp_close_connection_TDATA,
        vld_out => regslice_both_m_axis_tcp_close_connection_V_data_V_U_vld_out,
        ack_out => m_axis_tcp_close_connection_TREADY,
        apdone_blk => regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk);

    regslice_both_m_axis_tcp_close_connection_V_keep_V_U : component hls_recv_krnl_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv2_0,
        vld_in => m_axis_tcp_close_connection_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_tcp_close_connection_V_keep_V_U_ack_in_dummy,
        data_out => m_axis_tcp_close_connection_TKEEP,
        vld_out => regslice_both_m_axis_tcp_close_connection_V_keep_V_U_vld_out,
        ack_out => m_axis_tcp_close_connection_TREADY,
        apdone_blk => regslice_both_m_axis_tcp_close_connection_V_keep_V_U_apdone_blk);

    regslice_both_m_axis_tcp_close_connection_V_strb_V_U : component hls_recv_krnl_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv2_0,
        vld_in => m_axis_tcp_close_connection_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_tcp_close_connection_V_strb_V_U_ack_in_dummy,
        data_out => m_axis_tcp_close_connection_TSTRB,
        vld_out => regslice_both_m_axis_tcp_close_connection_V_strb_V_U_vld_out,
        ack_out => m_axis_tcp_close_connection_TREADY,
        apdone_blk => regslice_both_m_axis_tcp_close_connection_V_strb_V_U_apdone_blk);

    regslice_both_m_axis_tcp_close_connection_V_last_V_U : component hls_recv_krnl_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv1_0,
        vld_in => m_axis_tcp_close_connection_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_tcp_close_connection_V_last_V_U_ack_in_dummy,
        data_out => m_axis_tcp_close_connection_TLAST,
        vld_out => regslice_both_m_axis_tcp_close_connection_V_last_V_U_vld_out,
        ack_out => m_axis_tcp_close_connection_TREADY,
        apdone_blk => regslice_both_m_axis_tcp_close_connection_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_reg_76 = ap_const_lv1_1) and (m_axis_tcp_close_connection_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    tmp_reg_76(0) <= '1';

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_reg_76, closeConnection_empty_n, ap_block_state1_io, regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk, ap_block_state2_io, m_axis_tcp_close_connection_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1) or ((closeConnection_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (m_axis_tcp_close_connection_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_reg_76 = ap_const_lv1_1) and (m_axis_tcp_close_connection_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, tmp_nbreadreq_fu_38_p3, closeConnection_empty_n, m_axis_tcp_close_connection_TREADY_int_regslice)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((closeConnection_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (m_axis_tcp_close_connection_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state1_io_assign_proc : process(tmp_nbreadreq_fu_38_p3, m_axis_tcp_close_connection_TREADY_int_regslice)
    begin
                ap_block_state1_io <= ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (m_axis_tcp_close_connection_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(tmp_reg_76, regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk, m_axis_tcp_close_connection_TREADY_int_regslice)
    begin
                ap_block_state2 <= ((regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk = ap_const_logic_1) or ((tmp_reg_76 = ap_const_lv1_1) and (m_axis_tcp_close_connection_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state2_io_assign_proc : process(tmp_reg_76, m_axis_tcp_close_connection_TREADY_int_regslice)
    begin
                ap_block_state2_io <= ((tmp_reg_76 = ap_const_lv1_1) and (m_axis_tcp_close_connection_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, tmp_reg_76, regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk, ap_block_state2_io, m_axis_tcp_close_connection_TREADY_int_regslice)
    begin
        if ((not(((regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_reg_76 = ap_const_lv1_1) and (m_axis_tcp_close_connection_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, tmp_reg_76, regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk, ap_block_state2_io, m_axis_tcp_close_connection_TREADY_int_regslice)
    begin
        if ((not(((regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or ((tmp_reg_76 = ap_const_lv1_1) and (m_axis_tcp_close_connection_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    closeConnection_empty_n <= ap_const_logic_1;

    m_axis_tcp_close_connection_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, tmp_nbreadreq_fu_38_p3, ap_CS_fsm_state2, tmp_reg_76, m_axis_tcp_close_connection_TREADY_int_regslice)
    begin
        if ((((tmp_reg_76 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            m_axis_tcp_close_connection_TDATA_blk_n <= m_axis_tcp_close_connection_TREADY_int_regslice;
        else 
            m_axis_tcp_close_connection_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_tcp_close_connection_TVALID <= regslice_both_m_axis_tcp_close_connection_V_data_V_U_vld_out;

    m_axis_tcp_close_connection_TVALID_int_regslice_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, tmp_nbreadreq_fu_38_p3, closeConnection_empty_n, ap_block_state1_io, m_axis_tcp_close_connection_TREADY_int_regslice)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1) or ((closeConnection_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1)) or ((tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (m_axis_tcp_close_connection_TREADY_int_regslice = ap_const_logic_0)))) and (tmp_nbreadreq_fu_38_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axis_tcp_close_connection_TVALID_int_regslice <= ap_const_logic_1;
        else 
            m_axis_tcp_close_connection_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_nbreadreq_fu_38_p3 <= (0=>(closeConnection_empty_n), others=>'-');
end behav;
