catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project hls_recv_krnl
set_top hls_recv_krnl
# v++ -g, -D, -I, --advanced.prop kernel.hls_recv_krnl.kernel_flags
add_files "/space1/hxh/APB/sha_aes_tcpip/Vitis_with_100Gbps_TCP-IP/kernel/user_krnl/hls_recv_krnl/src/hls/hls_recv_krnl.cpp" -cflags " -I /space1/hxh/APB/sha_aes_tcpip/Vitis_with_100Gbps_TCP-IP/kernel/common/include "
open_solution -flow_target vitis solution
set_part xcu250-figd2104-2L-e
# v++ --hls.clock or --kernel_frequency
create_clock -period 200MHz -name default
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ --advanced.param compiler.deadlockDetection
config_export -disable_deadlock_detection=true
# v++ --advanced.param compiler.axiDeadLockFree
config_rtl -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format ip_catalog -ipname hls_recv_krnl
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
