// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_recv_krnl_tie_off_tcp_close_con (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axis_tcp_close_connection_TDATA,
        m_axis_tcp_close_connection_TVALID,
        m_axis_tcp_close_connection_TREADY,
        m_axis_tcp_close_connection_TKEEP,
        m_axis_tcp_close_connection_TSTRB,
        m_axis_tcp_close_connection_TLAST
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [15:0] m_axis_tcp_close_connection_TDATA;
output   m_axis_tcp_close_connection_TVALID;
input   m_axis_tcp_close_connection_TREADY;
output  [1:0] m_axis_tcp_close_connection_TKEEP;
output  [1:0] m_axis_tcp_close_connection_TSTRB;
output  [0:0] m_axis_tcp_close_connection_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    m_axis_tcp_close_connection_TDATA_blk_n;
wire   [0:0] tmp_nbreadreq_fu_38_p3;
wire    ap_CS_fsm_state2;
reg   [0:0] tmp_reg_76;
wire    closeConnection_empty_n;
reg    ap_block_state1;
reg    ap_block_state1_io;
wire    regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk;
reg    ap_block_state2;
reg    ap_block_state2_io;
reg   [1:0] ap_NS_fsm;
reg    m_axis_tcp_close_connection_TVALID_int_regslice;
wire    m_axis_tcp_close_connection_TREADY_int_regslice;
wire    regslice_both_m_axis_tcp_close_connection_V_data_V_U_vld_out;
wire    regslice_both_m_axis_tcp_close_connection_V_keep_V_U_apdone_blk;
wire    regslice_both_m_axis_tcp_close_connection_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_tcp_close_connection_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_tcp_close_connection_V_strb_V_U_apdone_blk;
wire    regslice_both_m_axis_tcp_close_connection_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_tcp_close_connection_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_tcp_close_connection_V_last_V_U_apdone_blk;
wire    regslice_both_m_axis_tcp_close_connection_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_tcp_close_connection_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

hls_recv_krnl_regslice_both #(
    .DataWidth( 16 ))
regslice_both_m_axis_tcp_close_connection_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(16'd0),
    .vld_in(m_axis_tcp_close_connection_TVALID_int_regslice),
    .ack_in(m_axis_tcp_close_connection_TREADY_int_regslice),
    .data_out(m_axis_tcp_close_connection_TDATA),
    .vld_out(regslice_both_m_axis_tcp_close_connection_V_data_V_U_vld_out),
    .ack_out(m_axis_tcp_close_connection_TREADY),
    .apdone_blk(regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk)
);

hls_recv_krnl_regslice_both #(
    .DataWidth( 2 ))
regslice_both_m_axis_tcp_close_connection_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(2'd0),
    .vld_in(m_axis_tcp_close_connection_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_tcp_close_connection_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_tcp_close_connection_TKEEP),
    .vld_out(regslice_both_m_axis_tcp_close_connection_V_keep_V_U_vld_out),
    .ack_out(m_axis_tcp_close_connection_TREADY),
    .apdone_blk(regslice_both_m_axis_tcp_close_connection_V_keep_V_U_apdone_blk)
);

hls_recv_krnl_regslice_both #(
    .DataWidth( 2 ))
regslice_both_m_axis_tcp_close_connection_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(2'd0),
    .vld_in(m_axis_tcp_close_connection_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_tcp_close_connection_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_tcp_close_connection_TSTRB),
    .vld_out(regslice_both_m_axis_tcp_close_connection_V_strb_V_U_vld_out),
    .ack_out(m_axis_tcp_close_connection_TREADY),
    .apdone_blk(regslice_both_m_axis_tcp_close_connection_V_strb_V_U_apdone_blk)
);

hls_recv_krnl_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_tcp_close_connection_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(1'd0),
    .vld_in(m_axis_tcp_close_connection_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_tcp_close_connection_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_tcp_close_connection_TLAST),
    .vld_out(regslice_both_m_axis_tcp_close_connection_V_last_V_U_vld_out),
    .ack_out(m_axis_tcp_close_connection_TREADY),
    .apdone_blk(regslice_both_m_axis_tcp_close_connection_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state2_io) | ((tmp_reg_76 == 1'd1) & (m_axis_tcp_close_connection_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((~((regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state2_io) | ((tmp_reg_76 == 1'd1) & (m_axis_tcp_close_connection_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state2_io) | ((tmp_reg_76 == 1'd1) & (m_axis_tcp_close_connection_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_76 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_38_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        m_axis_tcp_close_connection_TDATA_blk_n = m_axis_tcp_close_connection_TREADY_int_regslice;
    end else begin
        m_axis_tcp_close_connection_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b1 == ap_block_state1_io) | (ap_done_reg == 1'b1) | ((closeConnection_empty_n == 1'b0) & (tmp_nbreadreq_fu_38_p3 == 1'd1)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (m_axis_tcp_close_connection_TREADY_int_regslice == 1'b0))) & (tmp_nbreadreq_fu_38_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axis_tcp_close_connection_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_tcp_close_connection_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (1'b1 == ap_block_state1_io) | (ap_done_reg == 1'b1) | ((closeConnection_empty_n == 1'b0) & (tmp_nbreadreq_fu_38_p3 == 1'd1)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (m_axis_tcp_close_connection_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state2_io) | ((tmp_reg_76 == 1'd1) & (m_axis_tcp_close_connection_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((closeConnection_empty_n == 1'b0) & (tmp_nbreadreq_fu_38_p3 == 1'd1)) | ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (m_axis_tcp_close_connection_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state1_io = ((tmp_nbreadreq_fu_38_p3 == 1'd1) & (m_axis_tcp_close_connection_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((regslice_both_m_axis_tcp_close_connection_V_data_V_U_apdone_blk == 1'b1) | ((tmp_reg_76 == 1'd1) & (m_axis_tcp_close_connection_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = ((tmp_reg_76 == 1'd1) & (m_axis_tcp_close_connection_TREADY_int_regslice == 1'b0));
end

assign closeConnection_empty_n = 1'b1;

assign m_axis_tcp_close_connection_TVALID = regslice_both_m_axis_tcp_close_connection_V_data_V_U_vld_out;

assign tmp_nbreadreq_fu_38_p3 = closeConnection_empty_n;

always @ (posedge ap_clk) begin
    tmp_reg_76 <= 1'b1;
end

endmodule //hls_recv_krnl_tie_off_tcp_close_con
