// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_recv_krnl_listenPorts_entry37 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        basePort_dout,
        basePort_empty_n,
        basePort_read,
        useConn_dout,
        useConn_empty_n,
        useConn_read,
        basePort_out_din,
        basePort_out_full_n,
        basePort_out_write,
        useConn_out_din,
        useConn_out_full_n,
        useConn_out_write,
        useConn_out1_din,
        useConn_out1_full_n,
        useConn_out1_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] basePort_dout;
input   basePort_empty_n;
output   basePort_read;
input  [31:0] useConn_dout;
input   useConn_empty_n;
output   useConn_read;
output  [15:0] basePort_out_din;
input   basePort_out_full_n;
output   basePort_out_write;
output  [31:0] useConn_out_din;
input   useConn_out_full_n;
output   useConn_out_write;
output  [31:0] useConn_out1_din;
input   useConn_out1_full_n;
output   useConn_out1_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg basePort_read;
reg useConn_read;
reg basePort_out_write;
reg useConn_out_write;
reg useConn_out1_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    basePort_blk_n;
reg    useConn_blk_n;
reg    basePort_out_blk_n;
reg    useConn_out_blk_n;
reg    useConn_out1_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (useConn_out1_full_n == 1'b0) | (useConn_out_full_n == 1'b0) | (basePort_out_full_n == 1'b0) | (useConn_empty_n == 1'b0) | (basePort_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (useConn_out1_full_n == 1'b0) | (useConn_out_full_n == 1'b0) | (basePort_out_full_n == 1'b0) | (useConn_empty_n == 1'b0) | (basePort_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (useConn_out1_full_n == 1'b0) | (useConn_out_full_n == 1'b0) | (basePort_out_full_n == 1'b0) | (useConn_empty_n == 1'b0) | (basePort_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        basePort_blk_n = basePort_empty_n;
    end else begin
        basePort_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        basePort_out_blk_n = basePort_out_full_n;
    end else begin
        basePort_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (useConn_out1_full_n == 1'b0) | (useConn_out_full_n == 1'b0) | (basePort_out_full_n == 1'b0) | (useConn_empty_n == 1'b0) | (basePort_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        basePort_out_write = 1'b1;
    end else begin
        basePort_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (useConn_out1_full_n == 1'b0) | (useConn_out_full_n == 1'b0) | (basePort_out_full_n == 1'b0) | (useConn_empty_n == 1'b0) | (basePort_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        basePort_read = 1'b1;
    end else begin
        basePort_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        useConn_blk_n = useConn_empty_n;
    end else begin
        useConn_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        useConn_out1_blk_n = useConn_out1_full_n;
    end else begin
        useConn_out1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (useConn_out1_full_n == 1'b0) | (useConn_out_full_n == 1'b0) | (basePort_out_full_n == 1'b0) | (useConn_empty_n == 1'b0) | (basePort_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        useConn_out1_write = 1'b1;
    end else begin
        useConn_out1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        useConn_out_blk_n = useConn_out_full_n;
    end else begin
        useConn_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (useConn_out1_full_n == 1'b0) | (useConn_out_full_n == 1'b0) | (basePort_out_full_n == 1'b0) | (useConn_empty_n == 1'b0) | (basePort_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        useConn_out_write = 1'b1;
    end else begin
        useConn_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (useConn_out1_full_n == 1'b0) | (useConn_out_full_n == 1'b0) | (basePort_out_full_n == 1'b0) | (useConn_empty_n == 1'b0) | (basePort_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        useConn_read = 1'b1;
    end else begin
        useConn_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (useConn_out1_full_n == 1'b0) | (useConn_out_full_n == 1'b0) | (basePort_out_full_n == 1'b0) | (useConn_empty_n == 1'b0) | (basePort_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign basePort_out_din = basePort_dout[15:0];

assign useConn_out1_din = useConn_dout;

assign useConn_out_din = useConn_dout;

endmodule //hls_recv_krnl_listenPorts_entry37
